export const enum Action {
    PlayerConnected = 'Player:connected',
    PlayerReady = 'Player:Ready',
    PlayerGetDrunk = 'Player:Drunk',
    TakeBusFromAirport = 'Bus:From:Airport',
    TakeBusToGarage = 'Bus:To:Garage',
    PlayerEnterVehicle = 'Player:EnterVehicle',
    PlayerExitVehicle = 'Player:ExitVehicle',
    PlayerToggleCarWindow = 'Player:Toggle:Vehicle:Window',
    PlayerOpenCarWindow = 'Player:Open:Vehicle:Window',
    PlayerCloseCarWindow = 'Player:Close:Vehicle:Window',
    PlayerWhistleStart = 'Player:Sound:Whistle:Start',
    PlayerWhistleStop = 'Player:Sound:Whistle:Stop',
    PlayerPlayAnim = 'Player:Play:Animation',
    PlayerClearAnim = 'Player:Clear:Animation',
    PlayerPlaySound = 'Player:Play:Sound',
    PlayerToggleCarDoor = 'Player:Toggle:Vehicle:Door',
    PlayerOpenCarDoor = 'Player:Open:Vehicle:Door',
    PlayerCloseCarDoor = 'Player:Close:Vehicle:Door',
    PlayerUnstuck = 'PlayerHelp:Unstuck',
    PlayerPlayOpenMap = 'Player:Play:OpenMap',
    PlayerPlayDeathCam = 'Player:Play:Death:Cam',
    PedParamedicGetToCar = 'Ped:Paramedic:Get:To:Car',
    PedParamedicTakeToHospital = 'Ped:Paramedic:Take:To:Hospital',
}
